clubs = {
    'Arsenal': 'ARS',
    'Aston Villa': 'AVL',
    'Bournemouth': 'BOU',
    'Brentford': 'BRE',
    'Brighton': 'BRI',
    'Burnley': 'BUR',
    'Chelsea': 'CHE',
    'Crystal Palace': 'CRY',
    'Everton': 'EVE',
    'Fulham': 'FUL',
    'Ipswich': 'IPS',
    'Leeds': 'LEE',
    'Leicester': 'LEI',
    'Liverpool': 'LIV',
    'Luton': 'LUT',
    'Manchester City': 'MCI',
    'Man City': 'MCI',
    'Manchester United': 'MUN',
    'Man United': 'MUN',
    'Man Utd': 'MUN',
    'Newcastle': 'NEW',
    "Nott'm Forest": 'NFO',
    'Norwich': 'NOR',
    'Sheffield United': 'SHU',
    'Southampton': 'SOU',
    'Spurs': 'TOT',
    'Watford': 'WAT',
    'West Brom': 'WBA',
    'West Ham': 'WHU',
    'Wolves': 'WOL'
}